[project]
name = "analisis"
version = "0.1.0"
description = "Default template for PDM package"
dependencies = ["pandas>=2.3.3", "pathlib>=1.0.1"]
requires-python = "==3.12.*"


[tool.pdm]
distribution = false
